from flask import Flask, Blueprint, redirect, jsonify, json, session, render_template, request
#from common.Toke import *
from config.db import db, app, ma

class Informacion(db.Model):
    __tablename__ = "tblinfo_vuelo"
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    origen = db.Column(db.String(300))
    origen_aeropuerto = db.Column(db.String(300))
    escala1 = db.Column(db.String(300))
    escala1_aeropuerto = db.Column(db.String(300))
    escala2 = db.Column(db.String(300))
    escala2_aeropuerto = db.Column(db.String(300))
    destino = db.Column(db.String(300))
    destino_aeropuerto = db.Column(db.String(300))
    numero_escalas = db.Column(db.Integer)
    duracion_total = db.Column(db.Integer)
    idaN = db.Column(db.Integer)
    vueltaN = db.Column(db.Double)
    idaF = db.Column(db.Double)
    vueltaF = db.Column(db.Double)
    solo_idaN = db.Column(db.Double)
    solo_idaF = db.Column(db.Double)
    tarifaS = db.Column(db.Text)
    RestriccionestarifaS = db.Column(db.Text)
    tarifaM = db.Column(db.Text)
    RestriccionestarifaM = db.Column(db.Text)
    tarifaL = db.Column(db.Text)
    RestriccionestarifaL = db.Column(db.Text)
    
    
    def __init__(self, origen, origen_aeropuerto, escala1, escala1_aeropuerto, escala2, escala2_aeropuerto, destino, destino_aeropuerto, duracion_total, numero_escalas, idaN, vueltaN, idaF, vueltaF, solo_idaN, solo_idaF, tarifaS, RestriccionestarifaS, tarifaM, RestriccionestarifaM, tarifaL, RestriccionestarifaL):
        self.origen = origen
        self.origen_aeropuerto = origen_aeropuerto
        self.escala1 = escala1
        self.escala1_aeropuerto = escala1_aeropuerto
        self.escala2 = escala2
        self.escala2_aeropuerto = escala2_aeropuerto
        self.destino = destino
        self.destino_aeropuerto = destino_aeropuerto
        self.numero_escalas = numero_escalas
        self.duracion_total = duracion_total
        self.idaN = idaN
        self.vueltaN = vueltaN
        self.idaF = idaF
        self.vueltaF = vueltaF
        self.solo_idaN = solo_idaN
        self.solo_idaF = solo_idaF
        self.tarifaS = tarifaS
        self.RestriccionestarifaS = RestriccionestarifaS
        self.tarifaM = tarifaM
        self.RestriccionestarifaM = RestriccionestarifaM
        self.tarifaL = tarifaL
        self.RestriccionestarifaL = RestriccionestarifaL
        
vuelos_nacionales = [
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Medellín, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional José María Córdova (MDE), Medellín, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "205080",
        "vueltaN": "155500",
        "idaF": "361080",
        "vueltaF": "227555",
        "solo_idaN": "205080",
        "solo_idaF": "361080",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Cali, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional Alfonso Bonilla Aragón (CLO), Cali, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "186605",
        "vueltaN": "189605",
        "idaF": "269385",
        "vueltaF": "213355",
        "solo_idaN": "186605",
        "solo_idaF": "269385",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Barranquilla, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional Ernesto Cortissoz (BAQ), Barranquilla, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "220670",
        "vueltaN": "231770",
        "idaF": "197555",
        "vueltaF": "197555",
        "solo_idaN": "176555",
        "solo_idaF": "197555",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Pereira, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional Matecaña (PEI), Pereira, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "176555",
        "vueltaN": "176555",
        "idaF": "197555",
        "vueltaF": "197555",
        "solo_idaN": "176555",
        "solo_idaF": "197555",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Cúcuta, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional Camilo Daza (CUC), Cúcuta, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "317580",
        "vueltaN": "334580",
        "idaF": "491420",
        "vueltaF": "304580",
        "solo_idaN": "317580",
        "solo_idaF": "410600",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Santa Marta, Colombia",
        "destino_aeropuerto": "Aeropuerto Internacional Simón Bolívar (SMR), Santa Marta, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "317580",
        "vueltaN": "334580",
        "idaF": "491420",
        "vueltaF": "304580",
        "solo_idaN": "317580",
        "solo_idaF": "410600",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Pasto, Colombia",
        "destino_aeropuerto": "Aeropuerto Antonio Nariño (PSO), Pasto, Colombia",
        "numero_escalas": "0",
        "duracion_total": "1",
        "idaN": "213060",
        "vueltaN": "219480",
        "idaF": "315580",
        "vueltaF": "324580",
        "solo_idaN": "213060",
        "solo_idaF": "309330",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Leticia, Colombia",
        "destino_aeropuerto": "Aeropuerto Alfredo Vásquez Cobo (LET), Leticia, Colombia",
        "numero_escalas": "0",
        "duracion_total": "2",
        "idaN": "289700",
        "vueltaN": "290480",
        "idaF": "489700",
        "vueltaF": "324580",
        "solo_idaN": "289700",
        "solo_idaF": "290900",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
]
vuelos_directos = [
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Miami, EE. UU.",
        "destino-aeropuerto": "Aeropuerto Internacional de Miami (MIA), Miami, EE. UU.",
        "numero_escalas": "0",
        "duracion_total": "4",
        "idaN": "1084590",
        "vueltaN": "831770",
        "idaF": "1584590",
        "vueltaF": "999555",
        "solo_idaN": "1084590",
        "solo_idaF": "1584590",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Madrid, España",
        "destino_aeropuerto": "Aeropuerto Adolfo Suárez Madrid-Barajas (MAD), Madrid, España",
        "numero_escalas": "0",
        "duracion_total": "10",
        "idaN": "2290170",
        "vueltaN": "1451770",
        "idaF": "2662290",
        "vueltaF": "1551770",
        "solo_idaN": "2290170",
        "solo_idaF": "2662290",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Nueva York, Estados Unidos",
        "destino-aeropuerto": "Aeropuerto Internacional John F. Kennedy (JFK), Nueva York, EE. UU.",
        "numero_escalas": "0",
        "duracion_total": "6",
        "idaN": "1128565",
        "vueltaN": "1390050",
        "idaF": "1662290",
        "vueltaF": "1551770",
        "solo_idaN": "1128565",
        "solo_idaF": "1662290",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Sao Paulo, Brasil",
        "destino_aeropuerto": "Aeropuerto Internacional de Guarulhos (GRU), Sao Paulo, Brasil",
        "numero_escalas": "0",
        "duracion_total": "8",
        "idaN": "1979785",
        "vueltaN": "1479275",
        "idaF": "2345995",
        "vueltaF": "2418565",
        "solo_idaN": "1979785",
        "solo_idaF": "2345995",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Ciudad de México, México",
        "destino_aeropuerto": "Aeropuerto Internacional de la Ciudad de México (MEX), Ciudad de México, México",
        "numero_escalas": "0",
        "duracion_total": "5",
        "idaN": "1858445",
        "vueltaN": "1390050",
        "idaF": "2162290",
        "vueltaF": "1551770",
        "solo_idaN": "1128565",
        "solo_idaF": "1662290",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "París, Francia",
        "destino_aeropuerto": "Aeropuerto Charles de Gaulle (CDG), París, Francia",
        "numero_escalas": "0",
        "duracion_total": "11",
        "idaN": "2855615",
        "vueltaN": "2159445",
        "idaF": "8153660",
        "vueltaF": "7551770",
        "solo_idaN": "2855615",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Buenos Aires, Argentina",
        "destino_aeropuerto": "Aeropuerto Internacional Ministro Pistarini (EZE), Buenos Aires, Argentina",
        "numero_escalas": "0",
        "duracion_total": "9",
        "idaN": "1755615",
        "vueltaN": "1438455",
        "idaF": "2126660",
        "vueltaF": "1755615",
        "solo_idaN": "1755615",
        "solo_idaF": "2126660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Lima, Perú",
        "destino_aeropuerto": "Aeropuerto Internacional Jorge Chávez (LIM), Lima, Perú",
        "numero_escalas": "0",
        "duracion_total": "6",
        "idaN": "2855615",
        "vueltaN": "2159445",
        "idaF": "8153660",
        "vueltaF": "7551770",
        "solo_idaN": "2855615",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Roma, Italia",
        "destino_aeropuerto": "Aeropuerto de Roma-Fiumicino (FCO), Roma, Italia",
        "numero_escalas": "0",
        "duracion_total": "12",
        "idaN": "2951670",
        "vueltaN": "2159445",
        "idaF": "8232110",
        "vueltaF": "7551770",
        "solo_idaN": "2951670",
        "solo_idaF": "8232110",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "destino": "Toronto, Canadá",
        "destino_aeropuerto": "Aeropuerto Internacional Toronto Pearson (YYZ), Toronto, Canadá",
        "numero_escalas": "0",
        "duracion_total": "8",
        "idaN": "1503525",
        "vueltaN": "1029930",
        "idaF": "1709660",
        "vueltaF": "1551770",
        "solo_idaN": "1503525",
        "solo_idaF": "1709660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
]
vuelos_dos_escalas = [
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Londres, Reino Unido",
        "escala1_aeropuerto": "Aeropuerto Heathrow de Londres (LHR), Londres, Reino Unido",
        "escala2": "París, Francia",
        "escala2_aeropuerto": "Aeropuerto Charles de Gaulle (CDG), París, Francia",
        "numero_escalas": "2",
        "destino": "Sídney, Australia",
        "destino_aeropuerto": "Aeropuerto Kingsford Smith de Sídney (SYD), Sídney, Australia",
        "duracion_total": "26",
        "idaN": "5855615",
        "vueltaN": "4159445",
        "idaF": "8153660",
        "vueltaF": "7551770",
        "solo_idaN": "5855615",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Miami, EE. UU.",
        "escala1_aeropuerto": "Aeropuerto Internacional de Miami (MIA), Miami, EE. UU.",
        "escala2": "Madrid, España",
        "escala2_aeropuerto": "Aeropuerto Adolfo Suárez Madrid-Barajas (MAD), Madrid, España",
        "destino": "Melbourne, Australia",
        "destino_aeropuerto": "Aeropuerto de Brisbane (BNE), Brisbane, Australia",
        "numero_escalas": "2",
        "duracion_total": "30",
        "idaN": "6855615",
        "vueltaN": "4159445",
        "idaF": "8153660",
        "vueltaF": "6551770",
        "solo_idaN": "5855615",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Lima, Perú",
        "escala1_aeropuerto": "Aeropuerto Internacional Jorge Chávez (LIM), Lima, Perú",
        "escala2": "Los Ángeles, EE. UU.",
        "escala2_aeropuerto": "Aeropuerto Internacional de Los Ángeles (LAX), Los Ángeles, EE. UU.",
        "destino": "Nueva Delhi, India",
        "destino_aeropuerto": "Aeropuerto Internacional Indira Gandhi (DEL), Nueva Delhi, India",
        "numero_escalas": "2",
        "duracion_total": "28",
        "idaN": "7255445",
        "vueltaN": "7055335",
        "idaF": "8153660",
        "vueltaF": "7551770",
        "solo_idaN": "7255445",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Miami, EE. UU.",
        "escala1_aeropuerto": "Aeropuerto Internacional de Miami (MIA), Miami, EE. UU.",
        "escala2": "Atlanta, EE. UU.",
        "escala2_aeropuerto": "Aeropuerto Internacional Hartsfield-Jackson (ATL), Atlanta, EE. UU.",
        "destino": "Nueva Orleans, EE. UU.",
        "destino_aeropuerto": "Aeropuerto Internacional Louis Armstrong (MSY), Nueva Orleans, EE. UU.",
        "numero_escalas": "2",
        "duracion_total": "16",
        "idaN": "5855615",
        "vueltaN": "4159445",
        "idaF": "8153660",
        "vueltaF": "7551770",
        "solo_idaN": "5855615",
        "solo_idaF": "8153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Caracas, Venezuela",
        "escala1_aeropuerto": "Aeropuerto Internacional Simón Bolívar (CCS), Caracas, Venezuela",
        "escala2": "San Juan, Puerto Rico",
        "escala2_aeropuerto": "Aeropuerto Internacional Luis Muñoz Marín (SJU), San Juan, Puerto Rico",
        "destino": "La Habana, Cuba",
        "destino_aeropuerto": "Aeropuerto Internacional José Martí (HAV), La Habana, Cuba",
        "numero_escalas": "2",
        "duracion_total": "14",
        "idaN": "3205615",
        "vueltaN": "2159445",
        "idaF": "5153660",
        "vueltaF": "4551770",
        "solo_idaN": "3205615",
        "solo_idaF": "5153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Buenos Aires, Argentina",
        "escala1_aeropuerto": "Aeropuerto Internacional Ministro Pistarini (EZE), Buenos Aires, Argentina",
        "escala2": "Lisboa, Portugal",
        "escala2_aeropuerto": "Aeropuerto Humberto Delgado (LIS), Lisboa, Portugal",
        "destino": "Moscú, Rusia",
        "destino_aeropuerto": "Aeropuerto Internacional de Sheremétievo (SVO), Moscú, Rusia",
        "numero_escalas": "2",
        "duracion_total": "28",
        "idaN": "8855615",
        "vueltaN": "8159445",
        "idaF": "9153660",
        "vueltaF": "9551770",
        "solo_idaN": "8855615",
        "solo_idaF": "9153660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "Londres, Reino Unido",
        "escala1_aeropuerto": "Aeropuerto Heathrow de Londres (LHR), Londres, Reino Unido",
        "escala2": "París, Francia",
        "escala2_aeropuerto": "Aeropuerto Charles de Gaulle (CDG), París, Francia",
        "destino": "Roma, Italia",
        "destino_aeropuerto": "Aeropuerto Leonardo da Vinci-Fiumicino (FCO), Roma, Italia",
        "numero_escalas": "2",
        "duracion_total": "26",
        "idaN": "4240595",
        "vueltaN": "3240445",
        "idaF": "9134660",
        "vueltaF": "8551770",
        "solo_idaN": "4240595",
        "solo_idaF": "9134660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "escala1": "Los Ángeles, EE. UU.",
        "escala1_aeropuerto": "Aeropuerto Internacional de Los Ángeles (LAX), Los Ángeles, EE. UU.",
        "escala2": "Tokio, Japón",
        "escala2_aeropuerto": "Aeropuerto Internacional de Narita (NRT), Tokio, Japón",
        "destino": "Pekín, China",
        "destino_aeropuerto": "Aeropuerto Internacional de Pekín-Capital (PEK), Pekín, China",
        "numero_escalas": "2",
        "duracion_total": "32",
        "idaN": "4240595",
        "vueltaN": "3240445",
        "idaF": "9134660",
        "vueltaF": "8551770",
        "solo_idaN": "4240595",
        "solo_idaF": "9134660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
    {
        "origen": "Bogotá, Colombia",
        "origen_aeropuerto": "Aeropuerto Internacional El Dorado (BOG), Bogotá, Colombia",
        "escala1": "San Francisco, EE. UU.",
        "escala1_aeropuerto": "Aeropuerto Internacional de San Francisco (SFO), San Francisco, EE. UU.",
        "escala2": "Toronto, Canadá",
        "escala2_aeropuerto": "Aeropuerto Internacional de Toronto Pearson (YYZ), Toronto, Canadá",
        "destino": "Londres, Reino Unido",
        "destino_aeropuerto": "Aeropuerto Heathrow de Londres (LHR), Londres, Reino Unido",
        "numero_escalas": "2",
        "duracion_total": "26",
        "idaN": "3589415",
        "vueltaN": "3589415",
        "idaF": "6134660",
        "vueltaF": "6551770",
        "solo_idaN": "6134660",
        "solo_idaF": "9134660",
        "tarifaS": "1 equipaje de mano(10kg) + bolso <br> Acumula 3LM por cada USD",
        "RestriccionestarifaS": " Equipaje de bodega(23 kg) <br> Check-in en aeropuerto (Servicio con cargo adicional) <br> Asiento Economy (Servicio con cargo adicional) <br> Seleccion de asientos (Servicio con cargo adicional) <br> Cambios de vuelo (Servicio con cargo adicional) <br> Abordaje prioritario (Servicio con cargo adicional)",
        "tarifaM": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Economy",
        "RestriccionestarifaM": " Cambios de vuelo (Servicio con cargo adicional antes del vuelo) <br> Abordaje prioritario (Compralo al hacer check-in)",
        "tarifaL": "1 equipaje de mano(10kg) + bolso <br> Acumula LifeMiles <br> 1 Equipaje de bodega(23 kg) <br> Check-in gratis en aeropuerto <br> Asiento Plus <br> Cambios de vuelo <br> Reembolso",
        "RestriccionestarifaL": " Abordaje prioritario (Servicio con cargo adicional)",
    },
]

def create_aero():
    if Informacion.query.count() == 0:
        for aeropuerto_data in vuelos_nacionales + vuelos_directos + vuelos_dos_escalas:
            origen = aeropuerto_data.get('origen', '')
            origen_aeropuerto = aeropuerto_data.get('origen_aeropuerto', '')
            escala1 = aeropuerto_data.get('escala1', '')
            escala1_aeropuerto = aeropuerto_data.get('escala1_aeropuerto', '')
            escala2 = aeropuerto_data.get('escala2', '')
            escala2_aeropuerto = aeropuerto_data.get('escala2_aeropuerto', '')
            destino = aeropuerto_data.get('destino', '')
            destino_aeropuerto = aeropuerto_data.get('destino_aeropuerto', '')
            numero_escalas = aeropuerto_data.get('numero_escalas', 0)
            duracion_total = aeropuerto_data.get('duracion_total', 0)
            idaN = aeropuerto_data.get('idaN', 0)
            vueltaN = aeropuerto_data.get('vueltaN', 0)
            idaF = aeropuerto_data.get('idaF', 0)
            vueltaF = aeropuerto_data.get('vueltaF', 0)
            solo_idaN = aeropuerto_data.get('solo_idaN', 0)
            solo_idaF = aeropuerto_data.get('solo_idaF', 0)
            tarifaS = aeropuerto_data.get('tarifaS', '')
            RestriccionestarifaS = aeropuerto_data.get('RestriccionestarifaS', '')
            tarifaM = aeropuerto_data.get('tarifaM', '')
            RestriccionestarifaM = aeropuerto_data.get('RestriccionestarifaM', '')
            tarifaL = aeropuerto_data.get('tarifaL', '')
            RestriccionestarifaL = aeropuerto_data.get('RestriccionestarifaL', '')
           
            nuevo_infor = Informacion(
                origen=origen,
                origen_aeropuerto=origen_aeropuerto,
                escala1=escala1,
                escala1_aeropuerto=escala1_aeropuerto,
                escala2=escala2,
                escala2_aeropuerto=escala2_aeropuerto,
                destino=destino,
                destino_aeropuerto=destino_aeropuerto,
                numero_escalas=numero_escalas,
                duracion_total=duracion_total,
                idaN=idaN,
                vueltaN=vueltaN,
                idaF=idaF,
                vueltaF=vueltaF,
                solo_idaN=solo_idaN,
                solo_idaF=solo_idaF,
                tarifaS=tarifaS,
                RestriccionestarifaS = RestriccionestarifaS,
                tarifaM=tarifaM,
                RestriccionestarifaM = RestriccionestarifaM,
                tarifaL=tarifaL,
                RestriccionestarifaL = RestriccionestarifaL,
            )

            db.session.add(nuevo_infor)

        db.session.commit()

with app.app_context():
    db.create_all()
    create_aero()
            
            
class InfoSchema(ma.Schema):
    class Meta:
        fields = ('id', 'origen', 'origen_aeropuerto', 'destino', 'destino_aeropuerto', 'numero_escalas',
                  'duracion_total', 'idaN', 'vueltaN', 'idaF', 'vueltaF', 'solo_idaN', 'solo_idaF', 'tarifaS', 
                  'RestriccionestarifaS', 'tarifaM', 'RestriccionestarifaM', 'tarifaL', 'RestriccionestarifaL')